site_name: Fast Connect 3 Credential Insertion API
site_description: Reference and usage of Fast Connect API for Citrix Receiver for Windows 4.2 and later
theme_dir: citrix-sdk
markdown_extensions:
  - admonition
  - codehilite
  - toc:
     anchorlink: True

pages:
- Introduction: index.md
- What's new: whats-new.md
- Setting up your environment: setting-up-your-environment.md
- API functions: api-functions.md
- Launching Applications and Session Management using the Self Service Plug-in (SSP): launching-applications-and-session-management.md
- API examples: examples.md
